### ISSUE TITLE
this.player.ima.getAdsManager().setDisableCustomPlaybackForIOS10Plus(true) is not a function IOS - Chrome

### ISSUE THREAD

**Issue by damjan25** [googleads/videojs-ima#952]
I am getting error 
ima.getAdsManager().setDisableCustomPlaybackForIOS10Plus(true) is not a function on: Ios (v14) Chrome (v86). 
I am **not** getting this error on chrome v84 but after upgrading to v86 I am getting this error.

Ads auto play normally and everything works. I just found this error while trying to fix observer for pausing the video. I am not sure if there is no need for this function anymore on ios v14 chrome v86+ or is this a bug ? :thinking: 

Device: Iphone x 
Os: Ios v14
Browser: chrome v86

**Comment by Kiro705** [comment]
Hi @damjan25 ,

The getDisableCustomPlaybackForIOS10Plus() method is on ImaSdkSettings, please see the [documentation here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.ImaSdkSettings#getDisableCustomPlaybackForIOS10Plus). That would be why you are getting an error when calling via the AdsManager.

You can set this field by calling it via ImaSdkSettings before calling vjsPlayer.ima();

```
google.ima.settings.setDisableCustomPlaybackForIOS10Plus(true);

// ***

vjsPlayer.ima(imaOptions);
```
